### ISSUE TITLE
Non-translateable HUD text - MENU

### ISSUE THREAD

**Issue by DukeDukeEm** [DukeDukeEm/Translation_ShortestTripToEarth_German#35]
![image](https://user-images.githubusercontent.com/69652463/115388854-ab13a300-a1dc-11eb-862d-f7be73552c17.png)

**Comment by Dimon485** [comment]
didn't find it. maybe a picture

**Comment by DukeDukeEm** [comment]
wontfix

**Comment by DukeDukeEm** [comment]
wontfix
